name: Extract App Release
on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload Finished Artifact Container
        uses: actions/upload-artifact@v4
        with:
          name: conduit-app-package
          path: ${{ github.workspace }}
